[theme]
primaryColor = "#ff6699"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "monospace"
[server]

headless = true
enableCORS = false
enableXsrfProtection = true